[package]
name = "wasm-svg"
description = "My super awesome Rust & WebAssembly project addressing SVG!"
version = "0.1.0"
authors = ["Tobias Mucke <tobias.mucke@gmail.com"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[dependencies]
